Traceback (most recent call last):
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/aet/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
profile = ProfileReport(taxis, minimal=True, title="Profiling Report: Taxis Dataset")
profile.to_notebook_iframe()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeCheckError[0m                            Traceback (most recent call last)
Cell [0;32mIn[39], line 1[0m
[0;32m----> 1[0m profile [38;5;241m=[39m [43mProfileReport[49m[43m([49m[43mtaxis[49m[43m,[49m[43m [49m[43mminimal[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mtitle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mProfiling Report: Taxis Dataset[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m profile[38;5;241m.[39mto_notebook_iframe()

File [0;32m~/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/pandas_profiling/profile_report.py:48[0m, in [0;36mProfileReport.__init__[0;34m(self, df, minimal, explorative, sensitive, dark_mode, orange_mode, tsmode, sortby, sample, config_file, lazy, typeset, summarizer, config, **kwargs)[0m
[1;32m     45[0m _json [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m     46[0m config: Settings
[0;32m---> 48[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m(
[1;32m     49[0m     [38;5;28mself[39m,
[1;32m     50[0m     df: Optional[pd[38;5;241m.[39mDataFrame] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     51[0m     minimal: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     52[0m     explorative: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     53[0m     sensitive: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     54[0m     dark_mode: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     55[0m     orange_mode: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     56[0m     tsmode: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m     57[0m     sortby: Optional[[38;5;28mstr[39m] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     58[0m     sample: Optional[[38;5;28mdict[39m] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     59[0m     config_file: Union[Path, [38;5;28mstr[39m] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     60[0m     lazy: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mTrue[39;00m,
[1;32m     61[0m     typeset: Optional[VisionsTypeset] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     62[0m     summarizer: Optional[BaseSummarizer] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     63[0m     config: Optional[Settings] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     64[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m     65[0m ):
[1;32m     66[0m [38;5;250m    [39m[38;5;124;03m"""Generate a ProfileReport based on a pandas DataFrame[39;00m
[1;32m     67[0m 
[1;32m     68[0m [38;5;124;03m    Config processing order (in case of duplicate entries, entries later in the order are retained):[39;00m
[0;32m   (...)[0m
[1;32m     82[0m [38;5;124;03m        **kwargs: other arguments, for valid arguments, check the default configuration file.[39;00m
[1;32m     83[0m [38;5;124;03m    """[39;00m
[1;32m     85[0m     [38;5;28;01mif[39;00m df [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m lazy:

File [0;32m~/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/typeguard/_functions.py:138[0m, in [0;36mcheck_argument_types[0;34m(func_name, arguments, memo)[0m
[1;32m    135[0m         [38;5;28;01mraise[39;00m exc
[1;32m    137[0m [38;5;28;01mtry[39;00m:
[0;32m--> 138[0m     [43mcheck_type_internal[49m[43m([49m[43mvalue[49m[43m,[49m[43m [49m[43mannotation[49m[43m,[49m[43m [49m[43mmemo[49m[43m)[49m
[1;32m    139[0m [38;5;28;01mexcept[39;00m TypeCheckError [38;5;28;01mas[39;00m exc:
[1;32m    140[0m     qualname [38;5;241m=[39m qualified_name(value, add_class_prefix[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [0;32m~/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/typeguard/_checkers.py:761[0m, in [0;36mcheck_type_internal[0;34m(value, annotation, memo)[0m
[1;32m    759[0m     checker [38;5;241m=[39m lookup_func(origin_type, args, extras)
[1;32m    760[0m     [38;5;28;01mif[39;00m checker:
[0;32m--> 761[0m         [43mchecker[49m[43m([49m[43mvalue[49m[43m,[49m[43m [49m[43morigin_type[49m[43m,[49m[43m [49m[43margs[49m[43m,[49m[43m [49m[43mmemo[49m[43m)[49m
[1;32m    762[0m         [38;5;28;01mreturn[39;00m
[1;32m    764[0m [38;5;28;01mif[39;00m isclass(origin_type):

File [0;32m~/mambaforge/envs/py4ds2e/lib/python3.10/site-packages/typeguard/_checkers.py:410[0m, in [0;36mcheck_union[0;34m(value, origin_type, args, memo)[0m
[1;32m    405[0m         errors[get_type_name(type_)] [38;5;241m=[39m exc
[1;32m    407[0m formatted_errors [38;5;241m=[39m indent(
[1;32m    408[0m     [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m[38;5;241m.[39mjoin([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00merror[38;5;132;01m}[39;00m[38;5;124m"[39m [38;5;28;01mfor[39;00m key, error [38;5;129;01min[39;00m errors[38;5;241m.[39mitems()), [38;5;124m"[39m[38;5;124m  [39m[38;5;124m"[39m
[1;32m    409[0m )
[0;32m--> 410[0m [38;5;28;01mraise[39;00m TypeCheckError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mdid not match any element in the union:[39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00mformatted_errors[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mTypeCheckError[0m: argument "config_file" (None) did not match any element in the union:
  pathlib.Path: is not an instance of pathlib.Path
  str: is not an instance of str

