Traceback (most recent call last):
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# remove cell
import matplotlib_inline.backend_inline
import matplotlib.pyplot as plt

# Plot settings
plt.style.use("https://github.com/aeturrell/python4DS/raw/main/plot_style.txt")
matplotlib_inline.backend_inline.set_matplotlib_formats("svg")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mgaierror[0m                                  Traceback (most recent call last)
File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:1346[0m, in [0;36mAbstractHTTPHandler.do_open[0;34m(self, http_class, req, **http_conn_args)[0m
[1;32m   1345[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1346[0m     [43mh[49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[43mreq[49m[38;5;241;43m.[39;49m[43mget_method[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mreq[49m[38;5;241;43m.[39;49m[43mselector[49m[43m,[49m[43m [49m[43mreq[49m[38;5;241;43m.[39;49m[43mdata[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m
[1;32m   1347[0m [43m              [49m[43mencode_chunked[49m[38;5;241;43m=[39;49m[43mreq[49m[38;5;241;43m.[39;49m[43mhas_header[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mTransfer-encoding[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m)[49m
[1;32m   1348[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:1285[0m, in [0;36mHTTPConnection.request[0;34m(self, method, url, body, headers, encode_chunked)[0m
[1;32m   1284[0m [38;5;124;03m"""Send a complete request to the server."""[39;00m
[0;32m-> 1285[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_request[49m[43m([49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mbody[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:1331[0m, in [0;36mHTTPConnection._send_request[0;34m(self, method, url, body, headers, encode_chunked)[0m
[1;32m   1330[0m     body [38;5;241m=[39m _encode(body, [38;5;124m'[39m[38;5;124mbody[39m[38;5;124m'[39m)
[0;32m-> 1331[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mendheaders[49m[43m([49m[43mbody[49m[43m,[49m[43m [49m[43mencode_chunked[49m[38;5;241;43m=[39;49m[43mencode_chunked[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:1280[0m, in [0;36mHTTPConnection.endheaders[0;34m(self, message_body, encode_chunked)[0m
[1;32m   1279[0m     [38;5;28;01mraise[39;00m CannotSendHeader()
[0;32m-> 1280[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_output[49m[43m([49m[43mmessage_body[49m[43m,[49m[43m [49m[43mencode_chunked[49m[38;5;241;43m=[39;49m[43mencode_chunked[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:1040[0m, in [0;36mHTTPConnection._send_output[0;34m(self, message_body, encode_chunked)[0m
[1;32m   1039[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39m_buffer[:]
[0;32m-> 1040[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mmsg[49m[43m)[49m
[1;32m   1042[0m [38;5;28;01mif[39;00m message_body [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1043[0m 
[1;32m   1044[0m     [38;5;66;03m# create a consistent interface to message_body[39;00m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:980[0m, in [0;36mHTTPConnection.send[0;34m(self, data)[0m
[1;32m    979[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mauto_open:
[0;32m--> 980[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m    981[0m [38;5;28;01melse[39;00m:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:1447[0m, in [0;36mHTTPSConnection.connect[0;34m(self)[0m
[1;32m   1445[0m [38;5;124m"[39m[38;5;124mConnect to a host on a given (SSL) port.[39m[38;5;124m"[39m
[0;32m-> 1447[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m   1449[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_tunnel_host:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/http/client.py:946[0m, in [0;36mHTTPConnection.connect[0;34m(self)[0m
[1;32m    945[0m [38;5;124;03m"""Connect to the host and port specified in __init__."""[39;00m
[0;32m--> 946[0m [38;5;28mself[39m[38;5;241m.[39msock [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m
[1;32m    947[0m [43m    [49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhost[49m[43m,[49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mport[49m[43m)[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mtimeout[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msource_address[49m[43m)[49m
[1;32m    948[0m [38;5;66;03m# Might fail in OSs that don't implement TCP_NODELAY[39;00m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/socket.py:823[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address)[0m
[1;32m    822[0m err [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m--> 823[0m [38;5;28;01mfor[39;00m res [38;5;129;01min[39;00m [43mgetaddrinfo[49m[43m([49m[43mhost[49m[43m,[49m[43m [49m[43mport[49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[43mSOCK_STREAM[49m[43m)[49m:
[1;32m    824[0m     af, socktype, proto, canonname, sa [38;5;241m=[39m res

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/socket.py:954[0m, in [0;36mgetaddrinfo[0;34m(host, port, family, type, proto, flags)[0m
[1;32m    953[0m addrlist [38;5;241m=[39m []
[0;32m--> 954[0m [38;5;28;01mfor[39;00m res [38;5;129;01min[39;00m [43m_socket[49m[38;5;241;43m.[39;49m[43mgetaddrinfo[49m[43m([49m[43mhost[49m[43m,[49m[43m [49m[43mport[49m[43m,[49m[43m [49m[43mfamily[49m[43m,[49m[43m [49m[38;5;28;43mtype[39;49m[43m,[49m[43m [49m[43mproto[49m[43m,[49m[43m [49m[43mflags[49m[43m)[49m:
[1;32m    955[0m     af, socktype, proto, canonname, sa [38;5;241m=[39m res

[0;31mgaierror[0m: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

[0;31mURLError[0m                                  Traceback (most recent call last)
File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/matplotlib/style/core.py:127[0m, in [0;36muse[0;34m(style)[0m
[1;32m    126[0m [38;5;28;01mtry[39;00m:
[0;32m--> 127[0m     rc [38;5;241m=[39m [43mrc_params_from_file[49m[43m([49m[43mstyle[49m[43m,[49m[43m [49m[43muse_default_template[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[1;32m    128[0m     _apply_style(rc)

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/matplotlib/__init__.py:852[0m, in [0;36mrc_params_from_file[0;34m(fname, fail_on_error, use_default_template)[0m
[1;32m    838[0m [38;5;124;03m"""[39;00m
[1;32m    839[0m [38;5;124;03mConstruct a `RcParams` from file *fname*.[39;00m
[1;32m    840[0m 
[0;32m   (...)[0m
[1;32m    850[0m [38;5;124;03m    parameters specified in the file. (Useful for updating dicts.)[39;00m
[1;32m    851[0m [38;5;124;03m"""[39;00m
[0;32m--> 852[0m config_from_file [38;5;241m=[39m [43m_rc_params_in_file[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[43mfail_on_error[49m[38;5;241;43m=[39;49m[43mfail_on_error[49m[43m)[49m
[1;32m    854[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m use_default_template:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/matplotlib/__init__.py:778[0m, in [0;36m_rc_params_in_file[0;34m(fname, transform, fail_on_error)[0m
[1;32m    777[0m rc_temp [38;5;241m=[39m {}
[0;32m--> 778[0m [38;5;28;01mwith[39;00m _open_file_or_url(fname) [38;5;28;01mas[39;00m fd:
[1;32m    779[0m     [38;5;28;01mtry[39;00m:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/contextlib.py:119[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    118[0m [38;5;28;01mtry[39;00m:
[0;32m--> 119[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    120[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/matplotlib/__init__.py:748[0m, in [0;36m_open_file_or_url[0;34m(fname)[0m
[1;32m    745[0m     _log[38;5;241m.[39mdebug(
[1;32m    746[0m         [38;5;124m"[39m[38;5;124mCould not get certifi ssl context, https may not work.[39m[38;5;124m"[39m
[1;32m    747[0m     )
[0;32m--> 748[0m [38;5;28;01mwith[39;00m [43murllib[49m[38;5;241;43m.[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43murlopen[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[43mcontext[49m[38;5;241;43m=[39;49m[43mssl_ctx[49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m    749[0m     [38;5;28;01myield[39;00m (line[38;5;241m.[39mdecode([38;5;124m'[39m[38;5;124mutf-8[39m[38;5;124m'[39m) [38;5;28;01mfor[39;00m line [38;5;129;01min[39;00m f)

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:214[0m, in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    213[0m     opener [38;5;241m=[39m _opener
[0;32m--> 214[0m [38;5;28;01mreturn[39;00m [43mopener[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:517[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    516[0m sys[38;5;241m.[39maudit([38;5;124m'[39m[38;5;124murllib.Request[39m[38;5;124m'[39m, req[38;5;241m.[39mfull_url, req[38;5;241m.[39mdata, req[38;5;241m.[39mheaders, req[38;5;241m.[39mget_method())
[0;32m--> 517[0m response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m
[1;32m    519[0m [38;5;66;03m# post-process response[39;00m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:534[0m, in [0;36mOpenerDirector._open[0;34m(self, req, data)[0m
[1;32m    533[0m protocol [38;5;241m=[39m req[38;5;241m.[39mtype
[0;32m--> 534[0m result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhandle_open[49m[43m,[49m[43m [49m[43mprotocol[49m[43m,[49m[43m [49m[43mprotocol[49m[43m [49m[38;5;241;43m+[39;49m
[1;32m    535[0m [43m                          [49m[38;5;124;43m'[39;49m[38;5;124;43m_open[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mreq[49m[43m)[49m
[1;32m    536[0m [38;5;28;01mif[39;00m result:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:494[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    493[0m func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 494[0m result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    495[0m [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:1389[0m, in [0;36mHTTPSHandler.https_open[0;34m(self, req)[0m
[1;32m   1388[0m [38;5;28;01mdef[39;00m [38;5;21mhttps_open[39m([38;5;28mself[39m, req):
[0;32m-> 1389[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdo_open[49m[43m([49m[43mhttp[49m[38;5;241;43m.[39;49m[43mclient[49m[38;5;241;43m.[39;49m[43mHTTPSConnection[49m[43m,[49m[43m [49m[43mreq[49m[43m,[49m
[1;32m   1390[0m [43m        [49m[43mcontext[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_context[49m[43m,[49m[43m [49m[43mcheck_hostname[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check_hostname[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/urllib/request.py:1349[0m, in [0;36mAbstractHTTPHandler.do_open[0;34m(self, http_class, req, **http_conn_args)[0m
[1;32m   1348[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m
[0;32m-> 1349[0m     [38;5;28;01mraise[39;00m URLError(err)
[1;32m   1350[0m r [38;5;241m=[39m h[38;5;241m.[39mgetresponse()

[0;31mURLError[0m: <urlopen error [Errno 8] nodename nor servname provided, or not known>

The above exception was the direct cause of the following exception:

[0;31mOSError[0m                                   Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      5[0m [38;5;66;03m# Plot settings[39;00m
[0;32m----> 6[0m [43mplt[49m[38;5;241;43m.[39;49m[43mstyle[49m[38;5;241;43m.[39;49m[43muse[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mhttps://github.com/aeturrell/python4DS/raw/main/plot_style.txt[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      7[0m matplotlib_inline[38;5;241m.[39mbackend_inline[38;5;241m.[39mset_matplotlib_formats([38;5;124m"[39m[38;5;124msvg[39m[38;5;124m"[39m)

File [0;32m/opt/anaconda3/envs/python4DS/lib/python3.9/site-packages/matplotlib/style/core.py:130[0m, in [0;36muse[0;34m(style)[0m
[1;32m    128[0m     _apply_style(rc)
[1;32m    129[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIOError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 130[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m(
[1;32m    131[0m         [38;5;124m"[39m[38;5;132;01m{!r}[39;00m[38;5;124m not found in the style library and input is not a [39m[38;5;124m"[39m
[1;32m    132[0m         [38;5;124m"[39m[38;5;124mvalid URL or path; see `style.available` for list of [39m[38;5;124m"[39m
[1;32m    133[0m         [38;5;124m"[39m[38;5;124mavailable styles[39m[38;5;124m"[39m[38;5;241m.[39mformat(style)) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m

[0;31mOSError[0m: 'https://github.com/aeturrell/python4DS/raw/main/plot_style.txt' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
OSError: 'https://github.com/aeturrell/python4DS/raw/main/plot_style.txt' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles

